### ISSUE TITLE
Command to send only the PL from a message to a one-on-one

### ISSUE THREAD

**Issue by vaindil** [vaindil/wazebot#13]
Users sometimes need just the PL from a message, mainly for copy/pasting into WMEditor Lite.
- Message with extra text is sent
- User copy/pastes entire message
- User sends command to bot: `!wb pl <entire message>`
- Bot replies with only the PL.

**Comment by PesachZ** [comment]
I'd recommend that the bot reply should be in the same channel that the request is sent. The user will usually send it in a 1:1 HO, but occasion it may be sent in a group HO by an editor to show something to other editors in the group. Since it would only be sent by request, its not different than other commands. If one user is abusing it, I'm sure his fellow editors will remind him of the 1:1 option.

**Comment by vaindil** [comment]
@PesachZ I've updated the comment, that works for me.

**Comment by PesachZ** [comment]
Similar but derivative would be an option to strip the PL of any layer parameters as well. This can be done with a simple regex. I can get the code from the KML script if needed, or write a regex for you.
